name 'newrelic_npi'
maintainer 'Jakob Hilden'
maintainer_email 'jakob@railslove.com'
license 'mit'
description 'Installs/Configures newrelic npi'
long_description 'Installs/Configures newrelic npi'
version '0.1.0'
